name: "autoconf CI: running gup system tests"

# derived off c-cpp.yml

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Checkout submodules / prerequisites
      run: git submodule update --init --recursive
    - name: run configure script
      run: |
        chmod a+x ./configure *.sh
        ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make test
      run: make test
